
package Interfaz;

import clases.Agencia;
import clases.Pasajero;
import clases.Fichero;
import clases.PasajeroLE;
import clases.PasajeroLO;
import clases.Vuelo;
import clases.Vuelo_Comercial;
import clases.Vuelo_Privado;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;



public class Graphic_Interface extends javax.swing.JFrame {
    DefaultListModel arreglo_mod = new DefaultListModel();
    
    
    public Graphic_Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        SectionPanel = new javax.swing.JPanel();
        ADESTINY = new javax.swing.JLabel();
        Agencia = new javax.swing.JLabel();
        ListaOficialPasajeros = new javax.swing.JButton();
        ListaEsperaPasajeros = new javax.swing.JButton();
        ContarPasajeroxDestino = new javax.swing.JButton();
        BuscarVueloxPasajero = new javax.swing.JButton();
        MostrarVueloxDestino = new javax.swing.JButton();
        CalcularIngresoxVuelo = new javax.swing.JButton();
        Copyright = new javax.swing.JLabel();
        PanelInformacion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SectionPanel.setBackground(new java.awt.Color(0, 153, 255));

        ADESTINY.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
        ADESTINY.setForeground(new java.awt.Color(255, 255, 255));
        ADESTINY.setText("ADESTINY");

        Agencia.setFont(new java.awt.Font("Helvetica", 2, 10)); // NOI18N
        Agencia.setForeground(new java.awt.Color(255, 255, 255));
        Agencia.setText("AGENCIA DE VUELOS");

        ListaOficialPasajeros.setBackground(new java.awt.Color(255, 255, 255));
        ListaOficialPasajeros.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        ListaOficialPasajeros.setForeground(new java.awt.Color(0, 153, 255));
        ListaOficialPasajeros.setText("Lista Oficial de Pasajeros");
        ListaOficialPasajeros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), new java.awt.Color(102, 102, 102), null));
        ListaOficialPasajeros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListaOficialPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaOficialPasajerosActionPerformed(evt);
            }
        });

        ListaEsperaPasajeros.setBackground(new java.awt.Color(255, 255, 255));
        ListaEsperaPasajeros.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        ListaEsperaPasajeros.setForeground(new java.awt.Color(0, 153, 255));
        ListaEsperaPasajeros.setText("Lista de Espera Pasajeros");
        ListaEsperaPasajeros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), new java.awt.Color(102, 102, 102), null));
        ListaEsperaPasajeros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ListaEsperaPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaEsperaPasajerosActionPerformed(evt);
            }
        });

        ContarPasajeroxDestino.setBackground(new java.awt.Color(255, 255, 255));
        ContarPasajeroxDestino.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        ContarPasajeroxDestino.setForeground(new java.awt.Color(0, 153, 255));
        ContarPasajeroxDestino.setText("Contar Pasajeros por Destino");
        ContarPasajeroxDestino.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), new java.awt.Color(102, 102, 102), null));
        ContarPasajeroxDestino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ContarPasajeroxDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContarPasajeroxDestinoActionPerformed(evt);
            }
        });

        BuscarVueloxPasajero.setBackground(new java.awt.Color(255, 255, 255));
        BuscarVueloxPasajero.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        BuscarVueloxPasajero.setForeground(new java.awt.Color(0, 153, 255));
        BuscarVueloxPasajero.setText("Buscar vuelo por pasajero");
        BuscarVueloxPasajero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), new java.awt.Color(102, 102, 102), null));
        BuscarVueloxPasajero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BuscarVueloxPasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarVueloxPasajeroActionPerformed(evt);
            }
        });

        MostrarVueloxDestino.setBackground(new java.awt.Color(255, 255, 255));
        MostrarVueloxDestino.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        MostrarVueloxDestino.setForeground(new java.awt.Color(0, 153, 255));
        MostrarVueloxDestino.setText("Mostrar Vuelo por Destino");
        MostrarVueloxDestino.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), new java.awt.Color(102, 102, 102), null));
        MostrarVueloxDestino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MostrarVueloxDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarVueloxDestinoActionPerformed(evt);
            }
        });

        CalcularIngresoxVuelo.setBackground(new java.awt.Color(255, 255, 255));
        CalcularIngresoxVuelo.setFont(new java.awt.Font("Helvetica", 0, 16)); // NOI18N
        CalcularIngresoxVuelo.setForeground(new java.awt.Color(0, 153, 255));
        CalcularIngresoxVuelo.setText("Calcular ingresos por Vuelo");
        CalcularIngresoxVuelo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), new java.awt.Color(102, 102, 102), null));
        CalcularIngresoxVuelo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CalcularIngresoxVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularIngresoxVueloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SectionPanelLayout = new javax.swing.GroupLayout(SectionPanel);
        SectionPanel.setLayout(SectionPanelLayout);
        SectionPanelLayout.setHorizontalGroup(
            SectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SectionPanelLayout.createSequentialGroup()
                .addGroup(SectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SectionPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(ADESTINY))
                    .addGroup(SectionPanelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(Agencia))
                    .addGroup(SectionPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(ListaOficialPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SectionPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(ListaEsperaPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SectionPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(ContarPasajeroxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SectionPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(BuscarVueloxPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SectionPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(MostrarVueloxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SectionPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(CalcularIngresoxVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        SectionPanelLayout.setVerticalGroup(
            SectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SectionPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(ADESTINY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Agencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(ListaOficialPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(ListaEsperaPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(ContarPasajeroxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(BuscarVueloxPasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(MostrarVueloxDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(CalcularIngresoxVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        background.add(SectionPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 500));

        Copyright.setFont(new java.awt.Font("Helvetica", 1, 10)); // NOI18N
        Copyright.setForeground(new java.awt.Color(102, 102, 102));
        Copyright.setText("Copyright (c) 2024 ADESTINY Reserved Rights");
        background.add(Copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, -1, -1));

        PanelInformacion.setBackground(new java.awt.Color(153, 204, 255));
        PanelInformacion.setForeground(new java.awt.Color(0, 0, 0));
        PanelInformacion.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N

        javax.swing.GroupLayout PanelInformacionLayout = new javax.swing.GroupLayout(PanelInformacion);
        PanelInformacion.setLayout(PanelInformacionLayout);
        PanelInformacionLayout.setHorizontalGroup(
            PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        PanelInformacionLayout.setVerticalGroup(
            PanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        background.add(PanelInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 430, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListaOficialPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaOficialPasajerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaOficialPasajerosActionPerformed

    private void ListaEsperaPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaEsperaPasajerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListaEsperaPasajerosActionPerformed

    private void ContarPasajeroxDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContarPasajeroxDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContarPasajeroxDestinoActionPerformed

    private void BuscarVueloxPasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarVueloxPasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarVueloxPasajeroActionPerformed

    private void MostrarVueloxDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarVueloxDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarVueloxDestinoActionPerformed

    private void CalcularIngresoxVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularIngresoxVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalcularIngresoxVueloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graphic_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graphic_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graphic_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graphic_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        // Leer el Fichero
        Fichero.leerArchivo();
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graphic_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADESTINY;
    private javax.swing.JLabel Agencia;
    private javax.swing.JButton BuscarVueloxPasajero;
    private javax.swing.JButton CalcularIngresoxVuelo;
    private javax.swing.JButton ContarPasajeroxDestino;
    private javax.swing.JLabel Copyright;
    private javax.swing.JButton ListaEsperaPasajeros;
    private javax.swing.JButton ListaOficialPasajeros;
    private javax.swing.JButton MostrarVueloxDestino;
    private javax.swing.JPanel PanelInformacion;
    private javax.swing.JPanel SectionPanel;
    private javax.swing.JPanel background;
    // End of variables declaration//GEN-END:variables
}
